# Generated by Django 2.2.4 on 2019-08-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TripInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('path', models.FloatField()),
                ('time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TripParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_allowed_speed', models.FloatField()),
                ('max_allowed_speed', models.FloatField()),
                ('allowed_passengers_count', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_trip_params', to='request.Person')),
                ('passengers', models.ManyToManyField(related_name='passengers_trip_params', to='request.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='path',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Person'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='tripinterval',
            name='params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.TripParams'),
        ),
        migrations.AddField(
            model_name='tripinterval',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='start_trips_set', to='request.Place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='target_trips_set', to='request.Place'),
            preserve_default=False,
        ),
    ]
